apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "templates-manager.fullname" . }}
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: git-pull
            image: alpine/git
            args: ["-C", "/templates/{{ .Values.templatesRepository.name }}", "pull"]
            volumeMounts:
            - name: data
              mountPath: /templates
          restartPolicy: Never
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: {{ include "templates-manager.fullname" . }}