{{- $fullName := include "initializr-backend.fullname" . -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $fullName }}
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ $fullName }}
            image: alpine/git
            args: ["-C", "/templates", "pull"]
            volumeMounts:
            - name: templates-volume
              mountPath: /templates
          restartPolicy: Never
          volumes:
          - name: templates-volume
            persistentVolumeClaim:
              claimName: {{ $fullName }}
