apiVersion: v1
kind: Service
metadata:
  name: nfs-{{ include "initializr-backend.fullname" . }}
  labels:
{{ include "initializr-backend.labels" . | indent 4 }}
spec:
  type: ExternalName
  externalName: service-x.namespace-b.svc.cluster.local
  ports:
    #2049/TCP,2049/UDP,32803/TCP,32803/UDP,20048/TCP,20048/UDP,875/TCP,875/UDP,111/TCP,111/UDP,662/TCP,662/UDP
    # Open the ports required by the NFS server
    - name: nfs
      containerPort: 2049
      protocol: TCP
    - name: nfs-udp
      containerPort: 2049
      protocol: UDP
    - name: nlockmgr
      containerPort: 32803
      protocol: TCP
    - name: nlockmgr-udp
      containerPort: 32803
      protocol: UDP
    - name: mountd
      containerPort: 20048
      protocol: TCP
    - name: mountd-udp
      containerPort: 20048
      protocol: UDP
    - name: rquotad
      containerPort: 875
      protocol: TCP
    - name: rquotad-udp
      containerPort: 875
      protocol: UDP
    - name: rpcbind
      containerPort: 111
      protocol: TCP
    - name: rpcbind-udp
      containerPort: 111
      protocol: UDP
    - name: statd
      containerPort: 662
      protocol: TCP
    - name: statd-udp
      containerPort: 662
      protocol: UDP